// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIIrt6qCHtnumBVEqdxGDE6K075zvE1U',
    appId: '1:759805151421:web:3afd4a4a34de7811ff0fd4',
    messagingSenderId: '759805151421',
    projectId: 'ebookapp-feb96',
    authDomain: 'ebookapp-feb96.firebaseapp.com',
    storageBucket: 'ebookapp-feb96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8XqzbxnTd1gufJhr0p5lIRRKwuy3XBF4',
    appId: '1:759805151421:android:d7a2f5527887195fff0fd4',
    messagingSenderId: '759805151421',
    projectId: 'ebookapp-feb96',
    storageBucket: 'ebookapp-feb96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPXEYpQq6G0S1A-N0t9nSfOv3vRzpJUF0',
    appId: '1:759805151421:ios:2c736f949d06a385ff0fd4',
    messagingSenderId: '759805151421',
    projectId: 'ebookapp-feb96',
    storageBucket: 'ebookapp-feb96.firebasestorage.app',
    iosBundleId: 'com.example.ebookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPXEYpQq6G0S1A-N0t9nSfOv3vRzpJUF0',
    appId: '1:759805151421:ios:2c736f949d06a385ff0fd4',
    messagingSenderId: '759805151421',
    projectId: 'ebookapp-feb96',
    storageBucket: 'ebookapp-feb96.firebasestorage.app',
    iosBundleId: 'com.example.ebookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDIIrt6qCHtnumBVEqdxGDE6K075zvE1U',
    appId: '1:759805151421:web:8659a28f1a723db0ff0fd4',
    messagingSenderId: '759805151421',
    projectId: 'ebookapp-feb96',
    authDomain: 'ebookapp-feb96.firebaseapp.com',
    storageBucket: 'ebookapp-feb96.firebasestorage.app',
  );
}
